# Schema for the configuration files of the Gin theme.
gin.settings:
  type: theme_settings
  label: 'gin settings'
  mapping:
    preset_accent_color:
      type: string
      label: 'Preset accent color'
    preset_focus_color:
      type: string
      label: 'Preset focus color'
    enable_darkmode:
      type: boolean
      label: 'The dark mode'
    classic_toolbar:
      type: string
      label: 'The classic toolbar'
    icon_default:
      type: boolean
      label: 'Use default logo'
    icon_path:
      type: string
      label: 'Path to custom logo'
    high_contrast_mode:
      type: boolean
      label: 'High contrast mode'

# Schema for theme settings.
gin.third_party.shortcut:
  type: mapping
  label: 'Shortcut settings'
  mapping:
    module_link:
      type: boolean
      label: 'Add shortcut link'
